services:
  nanolimbo:
    image: diffusehyperion/nanolimbo:latest
    restart: unless-stopped
    container_name: nanolimbo
    ports:
      - 25565:65535
    volumes:
      - nanolimbo_data:/server
volumes:
  nanolimbo_data:
    name: nanolimbo_data
